version: '3.2'

services:
  php:
    build: ./images/php
    restart: always
    links:
      - pgsql
    env_file:
      - .env
    volumes:
      - ./public:/var/www/html
    ports:
      - "${APACHE_PORT}:80"

  pgsql:
    image: postgres:12.1
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}:5432"

  adminer:
    image: adminer:4.7.5
    restart: always
    env_file:
      - .env
    ports:
      - "${ADMINER_PORT}:8080"


